#############################################################
# BELMAI OS
# Satellite: BELMAI SAT-001
# Version: 0.2.0-alpha
# Author: Belmiro & Comunidade BELMAI OS
#############################################################

substitutions:
  device_name: belmai-sat-001
  friendly_name: BELMAI Satellite 001

packages:

  device: !include device.yaml

  wifi: !include ../../common/wifi.yaml

  api: !include ../../common/api.yaml

  ota: !include ../../common/ota.yaml

  diagnostics: !include ../../common/diagnostics.yaml

  microphone: !include ../../components/microphone.yaml

  speaker: !include ../../components/speaker.yaml
  
  led_status: !include ../../components/led_status.yaml

  voice_assistant: !include ../../components/voice_assistant.yaml


  #media_player: !include ../../components/media_player.yaml

#secrets: !include secrets
#led: !include led.yaml