#############################################################
# BELMAI OS
# Satellite: BELMAI SAT-001
# Version: 0.2.0-alpha
# Author: Belmiro & Comunidade BELMAI OS
#############################################################

substitutions:
  device_name: belmai-sat-001
  friendly_name: BELMAI Satellite 001

packages:

  # Identificação do dispositivo
  device: !include device.yaml

  # Conectividade
  wifi: !include wifi.yaml

  # Comunicação com Home Assistant
  api: !include api.yaml

  # Atualização OTA
  ota: !include ota.yaml

  # Diagnóstico
  diagnostics: !include diagnostics.yaml

  # Microfone
  microphone: !include microphone.yaml


#secrets: !include secrets
#led: !include led.yaml